# House Price Prediction

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from collections import OrderedDict
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.impute  import SimpleImputer
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor , VotingRegressor , AdaBoostRegressor , RandomForestRegressor
from sklearn.model_selection import KFold
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:.2f}'.format

In [393]:
train_data = pd.read_csv(r"train.csv")
train_data.head(5)

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [394]:
train_data.isna().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [395]:
test_data = pd.read_csv("test.csv")
test_data.head(5)

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [396]:
test_data.shape

(1459, 80)

In [397]:
test_data.isna().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

### Remove Duplicate values(check Id)

In [398]:
duplicates = train_data['Id'].duplicated()
train_data[duplicates]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [399]:
train_data.drop_duplicates(inplace=True)

### Remove values with no Id

In [400]:
no_id_data = train_data[train_data['Id'].isna()]
no_id_data

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [401]:
train_data = train_data[train_data['Id'].notna()]
train_data.head(5)

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

### Target Variables

In [402]:
x = train_data.drop(columns = ['SalePrice' , 'Id'])
y = train_data['SalePrice']

#### Transform Y using log1p transformation (previously used yeo-jhonson transformation)

In [403]:
scaler = StandardScaler()

y_log1p = np.log1p(y)
y_log1p_scaled = scaler.fit_transform(np.array(y_log1p).reshape(-1,1))

### Important Variables

In [404]:
ordinal_cols = ['LotShape','Utilities','LandSlope','ExterQual','ExterCond',
                'BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','HeatingQC','KitchenQual','Functional',
                'FireplaceQu','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence']



nominal_cols = ['MSZoning','Street','Alley','Neighborhood','LotConfig','BldgType','Condition1','Condition2','HouseStyle','LandContour','RoofStyle','RoofMatl','Exterior1st' ,'Exterior2nd' ,
                'MasVnrType' , 'Foundation' , 'Heating' , 'GarageType' , 'MiscFeature' , 'SaleType' , 'SaleCondition', 'Electrical' , 'CentralAir']



impute_constant_cols = ['MSSubClass','MSZoning','Street','LotShape','LandContour','Utilities','LotConfig','LandSlope',
                        'Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st',
                        'Exterior2nd','ExterQual','ExterCond','Foundation','Heating','HeatingQC','CentralAir','Electrical',
                        'BsmtFullBath','BsmtHalfBath','FullBath','HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual','Fireplaces','GarageCars',
                        'PavedDrive','SaleType','SaleCondition', 'Functional']


# cols whose na values can be filled with median
numerical_cols = ['MSSubClass','LotArea','LotFrontage','OverallQual','OverallCond','YearBuilt','YearRemodAdd',
                  'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','LowQualFinSF',
                  'GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd'
                  ,'Fireplaces','GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch'
                  ,'ScreenPorch','PoolArea','MiscVal','MoSold','YrSold']


# cols whose na values can be filled with default text values (like 'None' or 'No Garage')
# cols whose na values can be filled with 0
# (GarageYrBlt is kept here because if a house has no garage, a 0 is a safe placeholder before scaling/binarizing)
fill_default_cols = ['Alley','MasVnrType','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','FireplaceQu','GarageType',
                        'GarageFinish','GarageQual','GarageCond','PoolQC','Fence','MiscFeature' ,'GarageYrBlt']


default_map = {
    'Alley' : 'No alley',
    'MasVnrType' : 'None',
    'BsmtQual' : 'No Basement',
    'BsmtCond' : 'No Basement',
    'BsmtExposure' : 'No Basement',
    'BsmtFinType1' : 'No Basement',
    'BsmtFinType2' : 'No Basement',
    'FireplaceQu' : 'No Fireplace',
    'GarageType' : 'No Garage',
    'GarageFinish' : 'No Garage',
    'GarageQual' : 'No Garage',
    'GarageCond' : 'No Garage',
    'GarageYrBlt' : 0,
    'PoolQC' : 'No Pool',
    'Fence' : 'No Fence',
    'MiscFeature' : 'None'
}


ordinal_categories_map = {
'LotShape' : ['Missing' , 'IR3' , 'IR2' , 'IR1' , 'Reg'],
'Utilities' : ['Missing' , 'ELO' , 'NoSeWa' , 'NoSewr', 'AllPub'],
'LandSlope' : ['Missing' , 'Sev' , 'Mod' , 'Gtl'],
'ExterQual' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'ExterCond' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtQual' : ['No Basement' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtCond' : ['No Basement' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtExposure' : ['No Basement' , 'No' , 'Mn' , 'Av' , 'Gd'],
'BsmtFinType1' : ['No Basement' , 'Unf' , 'LwQ' , 'Rec' , 'BLQ' , 'ALQ' , 'GLQ'],
'BsmtFinType2' : ['No Basement' , 'Unf' , 'LwQ' , 'Rec' , 'BLQ' , 'ALQ' , 'GLQ'],
'HeatingQC' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'KitchenQual' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'Functional' :['Missing', 'Sal' , 'Sev' , 'Maj2' , 'Maj1' , 'Mod' , 'Min2' , 'Min1' , 'Typ'],
'FireplaceQu' : ['No Fireplace' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'GarageFinish' : ['No Garage' , 'Unf' , 'RFn' , 'Fin'],
'GarageQual' : ['No Garage' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'GarageCond' : ['No Garage' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'PavedDrive' : ['Missing' , 'N' , 'P' , 'Y'],
'PoolQC' : ['No Pool' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'Fence' : ['No Fence' , 'MnWw' , 'GdWo' , 'MnPrv' , 'GdPrv']
}


##different model Parameters
catboost_params = OrderedDict([('bagging_temperature',5.0), ('border_count',128), ('depth',6), ('iterations',5000), ('l2_leaf_reg',1), 
                               ('learning_rate',0.01), ('loss_function','RMSE'), ('random_state',42), ('task_type','GPU'), ('verbose',100)])
                              
trad_gbm_params = OrderedDict([('learning_rate', 0.1), ('loss', 'huber'), ('max_depth', 3), 
                               ('max_features', 'sqrt'), ('min_samples_split', 50), ('min_weight_fraction_leaf', 0.01),
                               ('n_estimators', 200), ('n_iter_no_change', 15), ('subsample', 1.0), 
                               ('validation_fraction', 0.15) , ('random_state',42)])

xgboost_params = OrderedDict([('colsample_bylevel', 0.6), ('colsample_bytree', 0.6), ('gamma', 0.1), 
                              ('grow_policy', 'depthwise'), ('learning_rate', 0.1), ('max_bin', 128), 
                              ('max_depth', 7), ('max_leaves', 127), ('min_child_weight', 7), 
                              ('reg_alpha', 0.5), ('reg_lambda', 5), ('subsample', 0.6) , ('random_state',42)])

lgbm_params = OrderedDict([('colsample_bynode', 0.8), ('colsample_bytree', 0.6), ('learning_rate', 0.05), 
                           ('max_bin', 512), ('max_depth', -1), ('min_child_samples', 20), 
                           ('min_child_weight', 10.0), ('min_split_gain', 0.1), ('n_estimators', 1000), 
                           ('num_leaves', 31), ('path_smooth', 5.0), ('reg_alpha', 0.1), ('reg_lambda', 1.0), 
                           ('subsample', 0.8), ('subsample_freq', 1) , ('random_state',42)])

adgbm_params = OrderedDict([('estimator' , DecisionTreeRegressor(max_depth=8 , min_samples_split=10)), 
                            ('learning_rate', 1.0), ('loss', 'square'), ('n_estimators', 500)])

rf_params = OrderedDict([('max_depth', 100), ('max_features', None), 
                         ('min_samples_split', 2), ('n_estimators', 300)])

### Fill Default value columns

In [405]:
for col in fill_default_cols:
    default_val = default_map.get(col)
    train_data[col] = train_data[col].fillna(default_val)
    test_data[col] = test_data[col].fillna(default_val)
    print(f"Default Values of {col} filled with {default_val}")
    print(train_data[col].unique())
    print(train_data[col].unique())

Default Values of Alley filled with No alley
['No alley' 'Grvl' 'Pave']
['No alley' 'Grvl' 'Pave']
Default Values of MasVnrType filled with None
['BrkFace' 'None' 'Stone' 'BrkCmn']
['BrkFace' 'None' 'Stone' 'BrkCmn']
Default Values of BsmtQual filled with No Basement
['Gd' 'TA' 'Ex' 'No Basement' 'Fa']
['Gd' 'TA' 'Ex' 'No Basement' 'Fa']
Default Values of BsmtCond filled with No Basement
['TA' 'Gd' 'No Basement' 'Fa' 'Po']
['TA' 'Gd' 'No Basement' 'Fa' 'Po']
Default Values of BsmtExposure filled with No Basement
['No' 'Gd' 'Mn' 'Av' 'No Basement']
['No' 'Gd' 'Mn' 'Av' 'No Basement']
Default Values of BsmtFinType1 filled with No Basement
['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'No Basement' 'LwQ']
['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'No Basement' 'LwQ']
Default Values of BsmtFinType2 filled with No Basement
['Unf' 'BLQ' 'No Basement' 'ALQ' 'Rec' 'LwQ' 'GLQ']
['Unf' 'BLQ' 'No Basement' 'ALQ' 'Rec' 'LwQ' 'GLQ']
Default Values of FireplaceQu filled with No Fireplace
['No Fireplace' 'TA' 'Gd' 'Fa' 'Ex' 'Po']
['No Fireplace' 'TA' 'Gd' 'Fa' 'Ex' 'Po']
Default Values of GarageType filled with No Garage
['Attchd' 'Detchd' 'BuiltIn' 'CarPort' 'No Garage' 'Basment' '2Types']
['Attchd' 'Detchd' 'BuiltIn' 'CarPort' 'No Garage' 'Basment' '2Types']
Default Values of GarageFinish filled with No Garage
['RFn' 'Unf' 'Fin' 'No Garage']
['RFn' 'Unf' 'Fin' 'No Garage']
Default Values of GarageQual filled with No Garage
['TA' 'Fa' 'Gd' 'No Garage' 'Ex' 'Po']
['TA' 'Fa' 'Gd' 'No Garage' 'Ex' 'Po']
Default Values of GarageCond filled with No Garage
['TA' 'Fa' 'No Garage' 'Gd' 'Po' 'Ex']
['TA' 'Fa' 'No Garage' 'Gd' 'Po' 'Ex']
Default Values of PoolQC filled with No Pool
['No Pool' 'Ex' 'Fa' 'Gd']
['No Pool' 'Ex' 'Fa' 'Gd']
Default Values of Fence filled with No Fence
['No Fence' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
['No Fence' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
Default Values of MiscFeature filled with None
['None' 'Shed' 'Gar2' 'Othr' 'TenC']
['None' 'Shed' 'Gar2' 'Othr' 'TenC']
Default Values of GarageYrBlt filled with 0
[2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.    0. 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]
[2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.    0. 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]

### Numerical Pipeline

In [406]:
num_pipeline = Pipeline(
    steps=[
        ('imputer' , SimpleImputer(strategy='median')),
        ('scaler' , StandardScaler())
    ]
)

### Ordinal Pipeline

In [407]:
ord_categories = [ordinal_categories_map.get(col) for col in ordinal_categories_map.keys()]
ord_categories

[['Missing', 'IR3', 'IR2', 'IR1', 'Reg'],
 ['Missing', 'ELO', 'NoSeWa', 'NoSewr', 'AllPub'],
 ['Missing', 'Sev', 'Mod', 'Gtl'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'No', 'Mn', 'Av', 'Gd'],
 ['No Basement', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
 ['No Basement', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ'],
 ['No Fireplace', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Garage', 'Unf', 'RFn', 'Fin'],
 ['No Garage', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Garage', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'N', 'P', 'Y'],
 ['No Pool', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Fence', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']]

In [408]:
ord_pipeline = Pipeline(
    steps=[
        ('imputer' , SimpleImputer(strategy='constant' , fill_value= 'Missing')),
        ('encoder' , OrdinalEncoder(categories= ord_categories , handle_unknown= 'use_encoded_value' , unknown_value=-1)),
        ('scaler' , StandardScaler())
    ]
)

### Nominal Pipeline

In [409]:
nom_pipeline = Pipeline(
    steps= [
        ('imputer' , SimpleImputer(strategy='constant' , fill_value='Missing')),
        ('encoder' , OneHotEncoder(handle_unknown='ignore' ,sparse_output = False)),
        ('scaler' , StandardScaler())
    ]
)

### Preprocessing Pipeline

In [410]:
preprocessing = ColumnTransformer(
    transformers= [
        ('num' , num_pipeline , numerical_cols),
        ('ord' , ord_pipeline , ordinal_cols),
        ('nom' , nom_pipeline , nominal_cols)
    ]
)

In [411]:
test_ids = test_data['Id']
test_data.drop(columns=['Id'] , inplace = True)

x = preprocessing.fit_transform(x)
test_data = preprocessing.transform(test_data)

### Main Pipeline

In [412]:
catboost_model = CatBoostRegressor(**catboost_params)
trad_gbm_model = GradientBoostingRegressor(**trad_gbm_params)
xgbm_model = XGBRegressor(**xgboost_params)
lgbm_model = LGBMRegressor(**lgbm_params)
adgbm_model = AdaBoostRegressor(**adgbm_params)
rf_model = RandomForestRegressor(**rf_params)

voting_model = VotingRegressor(
    estimators= [
        ('catboost', catboost_model),
        # ('xg_boost' , xgbm_model),
        ('light_gbm' , lgbm_model),
        ('trad_gbm' , trad_gbm_model)
        # ('adaboost' , adgbm_model),
        # ('rf' , rf_model)
    ]
)

voting_model.fit(x , y_log1p_scaled)

c:\Users\sohil\anaconda3\envs\AICourse\lib\site-packages\sklearn\ensemble\_voting.py:676: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0:	learn: 0.9926592	total: 13.1ms	remaining: 1m 5s
100:	learn: 0.5658583	total: 1.18s	remaining: 57.1s
200:	learn: 0.4010213	total: 2.53s	remaining: 1m
300:	learn: 0.3330339	total: 3.85s	remaining: 1m
400:	learn: 0.2995122	total: 5.11s	remaining: 58.7s
500:	learn: 0.2800291	total: 6.3s	remaining: 56.6s
600:	learn: 0.2673916	total: 7.57s	remaining: 55.4s
700:	learn: 0.2575019	total: 8.8s	remaining: 54s
800:	learn: 0.2500849	total: 9.91s	remaining: 52s
900:	learn: 0.2436013	total: 11.1s	remaining: 50.3s
1000:	learn: 0.2377960	total: 12.2s	remaining: 48.9s
1100:	learn: 0.2330649	total: 13.5s	remaining: 47.9s
1200:	learn: 0.2289161	total: 14.7s	remaining: 46.5s
1300:	learn: 0.2249357	total: 15.9s	remaining: 45.1s
1400:	learn: 0.2211434	total: 16.9s	remaining: 43.5s
1500:	learn: 0.2179208	total: 18s	remaining: 41.9s
1600:	learn: 0.2150698	total: 19.1s	remaining: 40.5s
1700:	learn: 0.2124701	total: 20.1s	remaining: 39.1s
1800:	learn: 0.2099124	total: 21.2s	remaining: 37.7s
1900:	learn: 0.2072835	total: 22.3s	remaining: 36.3s
2000:	learn: 0.2048808	total: 23.3s	remaining: 35s
2100:	learn: 0.2026261	total: 24.6s	remaining: 33.9s
2200:	learn: 0.2006977	total: 25.6s	remaining: 32.6s
2300:	learn: 0.1987803	total: 26.7s	remaining: 31.4s
2400:	learn: 0.1969133	total: 27.8s	remaining: 30.1s
2500:	learn: 0.1952530	total: 28.9s	remaining: 28.8s
2600:	learn: 0.1936496	total: 30s	remaining: 27.7s
2700:	learn: 0.1920024	total: 31.1s	remaining: 26.5s
2800:	learn: 0.1901906	total: 32.3s	remaining: 25.4s
2900:	learn: 0.1887976	total: 33.5s	remaining: 24.2s
3000:	learn: 0.1873333	total: 34.6s	remaining: 23s
3100:	learn: 0.1860120	total: 35.6s	remaining: 21.8s
3200:	learn: 0.1848169	total: 36.8s	remaining: 20.7s
3300:	learn: 0.1835884	total: 37.9s	remaining: 19.5s
3400:	learn: 0.1824564	total: 39s	remaining: 18.3s
3500:	learn: 0.1812273	total: 40.2s	remaining: 17.2s
3600:	learn: 0.1801097	total: 41.4s	remaining: 16.1s
3700:	learn: 0.1789617	total: 42.5s	remaining: 14.9s
3800:	learn: 0.1780026	total: 43.6s	remaining: 13.8s
3900:	learn: 0.1770927	total: 44.8s	remaining: 12.6s
4000:	learn: 0.1760438	total: 45.9s	remaining: 11.5s
4100:	learn: 0.1753258	total: 47.1s	remaining: 10.3s
4200:	learn: 0.1742532	total: 48.3s	remaining: 9.19s
4300:	learn: 0.1732835	total: 49.5s	remaining: 8.04s
4400:	learn: 0.1726319	total: 50.7s	remaining: 6.89s
4500:	learn: 0.1716692	total: 51.8s	remaining: 5.74s
4600:	learn: 0.1706885	total: 53s	remaining: 4.59s
4700:	learn: 0.1698724	total: 54.1s	remaining: 3.44s
4800:	learn: 0.1692133	total: 55.3s	remaining: 2.29s
4900:	learn: 0.1685191	total: 56.4s	remaining: 1.14s
4999:	learn: 0.1676658	total: 57.6s	remaining: 0us

VotingRegressor(estimators=[('catboost',
                             CatBoostRegressor(bagging_temperature=5.0, border_count=128, depth=6, iterations=5000, l2_leaf_reg=1, learning_rate=0.01, loss_function='RMSE', random_state=42, task_type='GPU', verbose=100)),
                            ('light_gbm',
                             LGBMRegressor(colsample_bynode=0.8,
                                           colsample_bytree=0.6,
                                           learning_rate=0.05, max_bin=512,
                                           min_child_weight=10.0,
                                           min_split_gain=0.1,
                                           n_estimators=1000, path_smooth=5.0,
                                           random_state=42, reg_alpha=0.1,
                                           reg_lambda=1.0, subsample=0.8,
                                           subsample_freq=1)),
                            ('trad_gbm',
                             GradientBoostingRegressor(loss='huber',
                                                       max_features='sqrt',
                                                       min_samples_split=50,
                                                       min_weight_fraction_leaf=0.01,
                                                       n_estimators=200,
                                                       n_iter_no_change=15,
                                                       random_state=42,
                                                       validation_fraction=0.15))])

In [414]:
scaled_transformed_predictions = voting_model.predict(test_data)

inverse_scaled_transformed_predictions = scaler.inverse_transform(np.array(scaled_transformed_predictions).reshape(-1,1))
actual_predictions = np.expm1(inverse_scaled_transformed_predictions)
rounded_actual_predictions = [ round(x,4) for x in actual_predictions.flatten()]

c:\Users\sohil\anaconda3\envs\AICourse\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [415]:
results = pd.DataFrame({
    "Id" : test_ids,
    "SalePrice" : rounded_actual_predictions
})

results.to_csv("result.csv" , index=False)