# House Price Prediction

In [326]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder , PowerTransformer
from sklearn.impute  import SimpleImputer
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import Dense , ELU , Dropout
from tensorflow.keras.regularizers import L1 , L2 , L1L2
from tensorflow.keras.losses import Huber
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential

pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:.2f}'.format

In [327]:
train_data = pd.read_csv(r"train.csv")
train_data.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.00,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.00,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.00,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.00,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.00,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [328]:
train_data.isna().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [329]:
test_data = pd.read_csv("test.csv")
test_data.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.00,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.00,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.00,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.00,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.00,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [330]:
test_data.shape

(1459, 80)

In [331]:
test_data.isna().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType        894
MasVnrArea         15
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinSF1          1
BsmtFinType2       42
BsmtFinSF2          1
BsmtUnfSF           1
TotalBsmtSF         1
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        2
BsmtHalfBath        2
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         1
TotRmsAbvGrd        0
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeature      1408
MiscVal             0
MoSold              0
YrSold              0
SaleType            1
SaleCondition       0
dtype: int64

### Remove Duplicate values(check Id)

In [332]:
duplicates = train_data['Id'].duplicated()
train_data[duplicates]

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [333]:
train_data.drop_duplicates(inplace=True)

### Remove values with no Id

In [334]:
no_id_data = train_data[train_data['Id'].isna()]
no_id_data

Empty DataFrame
Columns: [Id, MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandContour, Utilities, LotConfig, LandSlope, Neighborhood, Condition1, Condition2, BldgType, HouseStyle, OverallQual, OverallCond, YearBuilt, YearRemodAdd, RoofStyle, RoofMatl, Exterior1st, Exterior2nd, MasVnrType, MasVnrArea, ExterQual, ExterCond, Foundation, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, Heating, HeatingQC, CentralAir, Electrical, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscFeature, MiscVal, MoSold, YrSold, SaleType, SaleCondition, SalePrice]
Index: []

[0 rows x 81 columns]

In [335]:
train_data = train_data[train_data['Id'].notna()]
train_data.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.00,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.00,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.00,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.00,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.00,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

### Target Variables

In [336]:
x = train_data.drop(columns = ['SalePrice' , 'Id'])
y = train_data['SalePrice']

#### Transform Y using yeo-jhonson transformation

In [337]:
y_transformer = PowerTransformer(method='yeo-johnson' , standardize=True)
y_transformed = y_transformer.fit_transform(y.to_frame())

### Important Variables

In [338]:
ordinal_cols = ['LotShape','Utilities','LandSlope','ExterQual','ExterCond',
                'BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','HeatingQC','KitchenQual','Functional',
                'FireplaceQu','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence']



nominal_cols = ['MSZoning','Street','Alley','Neighborhood','LotConfig','BldgType','Condition1','Condition2','HouseStyle','LandContour','RoofStyle','RoofMatl','Exterior1st' ,'Exterior2nd' ,
                'MasVnrType' , 'Foundation' , 'Heating' , 'GarageType' , 'MiscFeature' , 'SaleType' , 'SaleCondition', 'Electrical' , 'CentralAir']



impute_constant_cols = ['MSSubClass','MSZoning','Street','LotShape','LandContour','Utilities','LotConfig','LandSlope',
                        'Neighborhood','Condition1','Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st',
                        'Exterior2nd','ExterQual','ExterCond','Foundation','Heating','HeatingQC','CentralAir','Electrical',
                        'BsmtFullBath','BsmtHalfBath','FullBath','HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual','Fireplaces','GarageCars',
                        'PavedDrive','SaleType','SaleCondition', 'Functional']


# cols whose na values can be filled with median
numerical_cols = ['MSSubClass','LotArea','LotFrontage','OverallQual','OverallCond','YearBuilt','YearRemodAdd',
                  'MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','1stFlrSF','2ndFlrSF','LowQualFinSF',
                  'GrLivArea','BsmtFullBath','BsmtHalfBath','FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd'
                  ,'Fireplaces','GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch'
                  ,'ScreenPorch','PoolArea','MiscVal','MoSold','YrSold']


# cols whose na values can be filled with default text values (like 'None' or 'No Garage')
# cols whose na values can be filled with 0
# (GarageYrBlt is kept here because if a house has no garage, a 0 is a safe placeholder before scaling/binarizing)
fill_default_cols = ['Alley','MasVnrType','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','FireplaceQu','GarageType',
                        'GarageFinish','GarageQual','GarageCond','PoolQC','Fence','MiscFeature' ,'GarageYrBlt']


default_map = {
    'Alley' : 'No alley',
    'MasVnrType' : 'None',
    'BsmtQual' : 'No Basement',
    'BsmtCond' : 'No Basement',
    'BsmtExposure' : 'No Basement',
    'BsmtFinType1' : 'No Basement',
    'BsmtFinType2' : 'No Basement',
    'FireplaceQu' : 'No Fireplace',
    'GarageType' : 'No Garage',
    'GarageFinish' : 'No Garage',
    'GarageQual' : 'No Garage',
    'GarageCond' : 'No Garage',
    'GarageYrBlt' : 0,
    'PoolQC' : 'No Pool',
    'Fence' : 'No Fence',
    'MiscFeature' : 'None'
}


ordinal_categories = {
'LotShape' : ['Missing' , 'IR3' , 'IR2' , 'IR1' , 'Reg'],
'Utilities' : ['Missing' , 'ELO' , 'NoSeWa' , 'NoSewr', 'AllPub'],
'LandSlope' : ['Missing' , 'Sev' , 'Mod' , 'Gtl'],
'ExterQual' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'ExterCond' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtQual' : ['No Basement' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtCond' : ['No Basement' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'BsmtExposure' : ['No Basement' , 'No' , 'Mn' , 'Av' , 'Gd'],
'BsmtFinType1' : ['No Basement' , 'Unf' , 'LwQ' , 'Rec' , 'BLQ' , 'ALQ' , 'GLQ'],
'BsmtFinType2' : ['No Basement' , 'Unf' , 'LwQ' , 'Rec' , 'BLQ' , 'ALQ' , 'GLQ'],
'HeatingQC' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'KitchenQual' : ['Missing' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'Functional' :['Missing', 'Sal' , 'Sev' , 'Maj2' , 'Maj1' , 'Mod' , 'Min2' , 'Min1' , 'Typ'],
'FireplaceQu' : ['No Fireplace' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'GarageFinish' : ['No Garage' , 'Unf' , 'RFn' , 'Fin'],
'GarageQual' : ['No Garage' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'GarageCond' : ['No Garage' , 'Po' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'PavedDrive' : ['Missing' , 'N' , 'P' , 'Y'],
'PoolQC' : ['No Pool' , 'Fa' , 'TA' , 'Gd' , 'Ex'],
'Fence' : ['No Fence' , 'MnWw' , 'GdWo' , 'MnPrv' , 'GdPrv']
}

### Fill Default value columns

In [339]:
for col in fill_default_cols:
    default_val = default_map.get(col)
    train_data[col] = train_data[col].fillna(default_val)
    test_data[col] = test_data[col].fillna(default_val)
    print(f"Default Values of {col} filled with {default_val}")
    print(train_data[col].unique())
    print(train_data[col].unique())

Default Values of Alley filled with No alley
['No alley' 'Grvl' 'Pave']
['No alley' 'Grvl' 'Pave']
Default Values of MasVnrType filled with None
['BrkFace' 'None' 'Stone' 'BrkCmn']
['BrkFace' 'None' 'Stone' 'BrkCmn']
Default Values of BsmtQual filled with No Basement
['Gd' 'TA' 'Ex' 'No Basement' 'Fa']
['Gd' 'TA' 'Ex' 'No Basement' 'Fa']
Default Values of BsmtCond filled with No Basement
['TA' 'Gd' 'No Basement' 'Fa' 'Po']
['TA' 'Gd' 'No Basement' 'Fa' 'Po']
Default Values of BsmtExposure filled with No Basement
['No' 'Gd' 'Mn' 'Av' 'No Basement']
['No' 'Gd' 'Mn' 'Av' 'No Basement']
Default Values of BsmtFinType1 filled with No Basement
['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'No Basement' 'LwQ']
['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' 'No Basement' 'LwQ']
Default Values of BsmtFinType2 filled with No Basement
['Unf' 'BLQ' 'No Basement' 'ALQ' 'Rec' 'LwQ' 'GLQ']
['Unf' 'BLQ' 'No Basement' 'ALQ' 'Rec' 'LwQ' 'GLQ']
Default Values of FireplaceQu filled with No Fireplace
['No Fireplace' 'TA' 'Gd' 'Fa' 'Ex' 'Po']
['No Fireplace' 'TA' 'Gd' 'Fa' 'Ex' 'Po']
Default Values of GarageType filled with No Garage
['Attchd' 'Detchd' 'BuiltIn' 'CarPort' 'No Garage' 'Basment' '2Types']
['Attchd' 'Detchd' 'BuiltIn' 'CarPort' 'No Garage' 'Basment' '2Types']
Default Values of GarageFinish filled with No Garage
['RFn' 'Unf' 'Fin' 'No Garage']
['RFn' 'Unf' 'Fin' 'No Garage']
Default Values of GarageQual filled with No Garage
['TA' 'Fa' 'Gd' 'No Garage' 'Ex' 'Po']
['TA' 'Fa' 'Gd' 'No Garage' 'Ex' 'Po']
Default Values of GarageCond filled with No Garage
['TA' 'Fa' 'No Garage' 'Gd' 'Po' 'Ex']
['TA' 'Fa' 'No Garage' 'Gd' 'Po' 'Ex']
Default Values of PoolQC filled with No Pool
['No Pool' 'Ex' 'Fa' 'Gd']
['No Pool' 'Ex' 'Fa' 'Gd']
Default Values of Fence filled with No Fence
['No Fence' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
['No Fence' 'MnPrv' 'GdWo' 'GdPrv' 'MnWw']
Default Values of MiscFeature filled with None
['None' 'Shed' 'Gar2' 'Othr' 'TenC']
['None' 'Shed' 'Gar2' 'Othr' 'TenC']
Default Values of GarageYrBlt filled with 0
[2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.    0. 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]
[2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.    0. 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]

### Numerical Pipeline

In [340]:
num_pipeline = Pipeline(
    steps=[
        ('imputer' , SimpleImputer(strategy='median')),
        ('scaler' , StandardScaler())
    ]
)

### Ordinal Pipeline

In [341]:
categories = [ordinal_categories.get(col) for col in ordinal_categories.keys()]
categories

[['Missing', 'IR3', 'IR2', 'IR1', 'Reg'],
 ['Missing', 'ELO', 'NoSeWa', 'NoSewr', 'AllPub'],
 ['Missing', 'Sev', 'Mod', 'Gtl'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Basement', 'No', 'Mn', 'Av', 'Gd'],
 ['No Basement', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
 ['No Basement', 'Unf', 'LwQ', 'Rec', 'BLQ', 'ALQ', 'GLQ'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'Sal', 'Sev', 'Maj2', 'Maj1', 'Mod', 'Min2', 'Min1', 'Typ'],
 ['No Fireplace', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Garage', 'Unf', 'RFn', 'Fin'],
 ['No Garage', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Garage', 'Po', 'Fa', 'TA', 'Gd', 'Ex'],
 ['Missing', 'N', 'P', 'Y'],
 ['No Pool', 'Fa', 'TA', 'Gd', 'Ex'],
 ['No Fence', 'MnWw', 'GdWo', 'MnPrv', 'GdPrv']]

In [342]:
ord_pipeline = Pipeline(
    steps=[
        ('imputer' , SimpleImputer(strategy='constant' , fill_value= 'Missing')),
        ('encoder' , OrdinalEncoder(categories= categories , handle_unknown= 'use_encoded_value' , unknown_value=-1)),
        ('scaler' , StandardScaler())
    ]
)

### Nominal Pipeline

In [343]:
nom_pipeline = Pipeline(
    steps= [
        ('imputer' , SimpleImputer(strategy='constant' , fill_value='Missing')),
        ('encoder' , OneHotEncoder(handle_unknown='ignore' ,sparse_output = False)),
        ('scaler' , StandardScaler())
    ]
)

### Preprocessing Pipeline

In [344]:
preprocessing = ColumnTransformer(
    transformers= [
        ('num' , num_pipeline , numerical_cols),
        ('ord' , ord_pipeline , ordinal_cols),
        ('nom' , nom_pipeline , nominal_cols)
    ]
)

### Model Pipeline

In [345]:
test_ids = test_data['Id']
test_data = test_data.drop(columns = ['Id'])

In [346]:
x = preprocessing.fit_transform(x)
test_data = preprocessing.transform(test_data)

In [347]:
x.shape

(1460, 226)

In [348]:
model = Sequential([
    Dense(64 , activation='relu' , kernel_initializer='he_normal' , bias_initializer= 'he_normal' ,kernel_regularizer = L1L2(0.01) , bias_regularizer= L1L2(0.01) ,input_shape = (226,)),
    ELU(alpha=0.01),
    Dropout(0.3),
    Dense(32 , activation='relu' , kernel_initializer='he_normal' , bias_regularizer= L1L2(0.01) ,kernel_regularizer = L1L2(0.01)),
    ELU(alpha = 0.01),
    Dense(1 , activation='linear')
])

c:\Users\sohil\anaconda3\envs\AICourse\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [349]:
model.compile(
    optimizer = Adam(learning_rate=0.01),
    loss = Huber(),
    metrics = ['mean_squared_error']
)

In [350]:
model.fit(
    x , y_transformed ,
    epochs = 1000,
    batch_size = 32,
    verbose = 1
)

Epoch 1/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5.7256 - mean_squared_error: 0.8306
Epoch 2/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.9822 - mean_squared_error: 0.2379
Epoch 3/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5843 - mean_squared_error: 0.2530
Epoch 4/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5061 - mean_squared_error: 0.2734
Epoch 5/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4961 - mean_squared_error: 0.2738
Epoch 6/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5062 - mean_squared_error: 0.2959
Epoch 7/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5015 - mean_squared_error: 0.2893
Epoch 8/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.4975 - mean_squared_error: 0.2794
Epoch 9/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4997 - mean_squared_error: 0.2763
Epoch 10/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4842 - mean_squared_error: 0.2267
Epoch 11/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5007 - mean_squared_error: 0.2650
Epoch 12/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4896 - mean_squared_error: 0.2482
Epoch 13/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4965 - mean_squared_error: 0.2819
Epoch 14/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5022 - mean_squared_error: 0.2674
Epoch 15/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5185 - mean_squared_error: 0.2828
Epoch 16/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4775 - mean_squared_error: 0.2409
Epoch 17/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4889 - mean_squared_error: 0.2604
Epoch 18/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5139 - mean_squared_error: 0.2643
Epoch 19/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4856 - mean_squared_error: 0.2658
Epoch 20/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5006 - mean_squared_error: 0.2519
Epoch 21/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5098 - mean_squared_error: 0.2717
Epoch 22/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5005 - mean_squared_error: 0.2552
Epoch 23/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4947 - mean_squared_error: 0.2695
Epoch 24/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5126 - mean_squared_error: 0.2548
Epoch 25/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5095 - mean_squared_error: 0.2554
Epoch 26/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5013 - mean_squared_error: 0.2642
Epoch 27/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4963 - mean_squared_error: 0.2541
Epoch 28/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4979 - mean_squared_error: 0.2375
Epoch 29/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5047 - mean_squared_error: 0.2490
Epoch 30/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5012 - mean_squared_error: 0.2659
Epoch 31/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5108 - mean_squared_error: 0.2790
Epoch 32/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4984 - mean_squared_error: 0.2490
Epoch 33/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5125 - mean_squared_error: 0.2608
Epoch 34/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4987 - mean_squared_error: 0.2624
Epoch 35/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5199 - mean_squared_error: 0.2671
Epoch 36/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5094 - mean_squared_error: 0.2358
Epoch 37/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5172 - mean_squared_error: 0.2650
Epoch 38/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5161 - mean_squared_error: 0.2736
Epoch 39/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5074 - mean_squared_error: 0.2557
Epoch 40/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4901 - mean_squared_error: 0.2499
Epoch 41/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5050 - mean_squared_error: 0.2668
Epoch 42/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5038 - mean_squared_error: 0.2610
Epoch 43/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5067 - mean_squared_error: 0.2648
Epoch 44/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4988 - mean_squared_error: 0.2659
Epoch 45/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5223 - mean_squared_error: 0.2758
Epoch 46/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4932 - mean_squared_error: 0.2326
Epoch 47/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5032 - mean_squared_error: 0.2569
Epoch 48/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4929 - mean_squared_error: 0.2690
Epoch 49/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5081 - mean_squared_error: 0.2479
Epoch 50/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5062 - mean_squared_error: 0.2675
Epoch 51/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4992 - mean_squared_error: 0.2833
Epoch 52/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5002 - mean_squared_error: 0.2611
Epoch 53/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5045 - mean_squared_error: 0.2710
Epoch 54/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5128 - mean_squared_error: 0.2792
Epoch 55/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4898 - mean_squared_error: 0.2472
Epoch 56/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4993 - mean_squared_error: 0.2953
Epoch 57/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4883 - mean_squared_error: 0.2942
Epoch 58/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5138 - mean_squared_error: 0.2826
Epoch 59/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4941 - mean_squared_error: 0.2728
Epoch 60/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4856 - mean_squared_error: 0.2802
Epoch 61/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4967 - mean_squared_error: 0.2670
Epoch 62/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4855 - mean_squared_error: 0.2541
Epoch 63/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4735 - mean_squared_error: 0.2695
Epoch 64/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5005 - mean_squared_error: 0.2681
Epoch 65/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4918 - mean_squared_error: 0.2829
Epoch 66/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4927 - mean_squared_error: 0.2704
Epoch 67/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5009 - mean_squared_error: 0.2732
Epoch 68/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4892 - mean_squared_error: 0.2831
Epoch 69/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5246 - mean_squared_error: 0.2786
Epoch 70/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5347 - mean_squared_error: 0.2897
Epoch 71/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5462 - mean_squared_error: 0.2439
Epoch 72/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5634 - mean_squared_error: 0.2679
Epoch 73/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5260 - mean_squared_error: 0.2431
Epoch 74/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5423 - mean_squared_error: 0.2697
Epoch 75/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5648 - mean_squared_error: 0.2727
Epoch 76/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5453 - mean_squared_error: 0.2644
Epoch 77/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5439 - mean_squared_error: 0.2830
Epoch 78/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5574 - mean_squared_error: 0.2870
Epoch 79/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6301 - mean_squared_error: 0.2462
Epoch 80/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6455 - mean_squared_error: 0.2656
Epoch 81/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6024 - mean_squared_error: 0.2579
Epoch 82/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5778 - mean_squared_error: 0.2654
Epoch 83/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5693 - mean_squared_error: 0.2443
Epoch 84/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5690 - mean_squared_error: 0.2510
Epoch 85/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5802 - mean_squared_error: 0.2468
Epoch 86/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5964 - mean_squared_error: 0.2716
Epoch 87/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5815 - mean_squared_error: 0.2522
Epoch 88/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5848 - mean_squared_error: 0.2709
Epoch 89/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5466 - mean_squared_error: 0.2873
Epoch 90/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5306 - mean_squared_error: 0.2908
Epoch 91/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5362 - mean_squared_error: 0.2563
Epoch 92/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5525 - mean_squared_error: 0.2623
Epoch 93/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5715 - mean_squared_error: 0.2729
Epoch 94/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6219 - mean_squared_error: 0.2788
Epoch 95/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6396 - mean_squared_error: 0.2885
Epoch 96/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6509 - mean_squared_error: 0.2905
Epoch 97/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6508 - mean_squared_error: 0.2989
Epoch 98/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5584 - mean_squared_error: 0.2270
Epoch 99/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5654 - mean_squared_error: 0.3140
Epoch 100/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5318 - mean_squared_error: 0.2766
Epoch 101/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5730 - mean_squared_error: 0.2602
Epoch 102/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5369 - mean_squared_error: 0.2832
Epoch 103/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5545 - mean_squared_error: 0.2881
Epoch 104/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5998 - mean_squared_error: 0.2808
Epoch 105/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6144 - mean_squared_error: 0.2813
Epoch 106/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6413 - mean_squared_error: 0.2765
Epoch 107/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6449 - mean_squared_error: 0.2943
Epoch 108/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6798 - mean_squared_error: 0.2978
Epoch 109/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5480 - mean_squared_error: 0.2432
Epoch 110/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5409 - mean_squared_error: 0.2662
Epoch 111/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5260 - mean_squared_error: 0.2713
Epoch 112/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4813 - mean_squared_error: 0.2756
Epoch 113/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4911 - mean_squared_error: 0.2511
Epoch 114/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5051 - mean_squared_error: 0.2554
Epoch 115/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5121 - mean_squared_error: 0.2712
Epoch 116/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4995 - mean_squared_error: 0.2583
Epoch 117/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5105 - mean_squared_error: 0.2593
Epoch 118/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5467 - mean_squared_error: 0.2524
Epoch 119/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5320 - mean_squared_error: 0.2573
Epoch 120/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5436 - mean_squared_error: 0.2505
Epoch 121/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5471 - mean_squared_error: 0.2631
Epoch 122/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5168 - mean_squared_error: 0.2609
Epoch 123/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5057 - mean_squared_error: 0.2504
Epoch 124/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5095 - mean_squared_error: 0.2508
Epoch 125/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5082 - mean_squared_error: 0.2759
Epoch 126/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5142 - mean_squared_error: 0.2766
Epoch 127/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4927 - mean_squared_error: 0.2440
Epoch 128/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4776 - mean_squared_error: 0.2399
Epoch 129/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4992 - mean_squared_error: 0.2663
Epoch 130/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5020 - mean_squared_error: 0.2665
Epoch 131/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5091 - mean_squared_error: 0.2856
Epoch 132/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5530 - mean_squared_error: 0.2773
Epoch 133/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5510 - mean_squared_error: 0.2661
Epoch 134/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5781 - mean_squared_error: 0.2562
Epoch 135/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5872 - mean_squared_error: 0.2778
Epoch 136/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5790 - mean_squared_error: 0.2432
Epoch 137/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5619 - mean_squared_error: 0.2686
Epoch 138/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5397 - mean_squared_error: 0.2753
Epoch 139/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5288 - mean_squared_error: 0.2582
Epoch 140/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5403 - mean_squared_error: 0.2746
Epoch 141/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5401 - mean_squared_error: 0.2480
Epoch 142/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5435 - mean_squared_error: 0.2487
Epoch 143/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5373 - mean_squared_error: 0.2849
Epoch 144/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5099 - mean_squared_error: 0.2419
Epoch 145/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5131 - mean_squared_error: 0.2741
Epoch 146/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5423 - mean_squared_error: 0.3018
Epoch 147/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5080 - mean_squared_error: 0.2553
Epoch 148/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5458 - mean_squared_error: 0.2679
Epoch 149/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4956 - mean_squared_error: 0.2557
Epoch 150/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5066 - mean_squared_error: 0.2761
Epoch 151/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5402 - mean_squared_error: 0.3015
Epoch 152/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5293 - mean_squared_error: 0.2712
Epoch 153/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5514 - mean_squared_error: 0.2921
Epoch 154/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5434 - mean_squared_error: 0.2545
Epoch 155/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5465 - mean_squared_error: 0.2467
Epoch 156/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5174 - mean_squared_error: 0.2372
Epoch 157/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5186 - mean_squared_error: 0.2862
Epoch 158/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5845 - mean_squared_error: 0.3502
Epoch 159/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6636 - mean_squared_error: 0.2745
Epoch 160/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6457 - mean_squared_error: 0.2897
Epoch 161/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5623 - mean_squared_error: 0.2701
Epoch 162/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5527 - mean_squared_error: 0.2877
Epoch 163/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5621 - mean_squared_error: 0.2586
Epoch 164/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5618 - mean_squared_error: 0.2859
Epoch 165/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5765 - mean_squared_error: 0.2716
Epoch 166/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5828 - mean_squared_error: 0.2759
Epoch 167/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5444 - mean_squared_error: 0.2654
Epoch 168/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5888 - mean_squared_error: 0.2733
Epoch 169/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6063 - mean_squared_error: 0.3033
Epoch 170/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5640 - mean_squared_error: 0.2809
Epoch 171/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5630 - mean_squared_error: 0.2786
Epoch 172/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6053 - mean_squared_error: 0.2780
Epoch 173/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5969 - mean_squared_error: 0.2958
Epoch 174/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6194 - mean_squared_error: 0.2829
Epoch 175/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5598 - mean_squared_error: 0.2933
Epoch 176/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5647 - mean_squared_error: 0.2721
Epoch 177/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5438 - mean_squared_error: 0.2895
Epoch 178/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5394 - mean_squared_error: 0.2569
Epoch 179/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5443 - mean_squared_error: 0.2682
Epoch 180/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5646 - mean_squared_error: 0.2698
Epoch 181/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5779 - mean_squared_error: 0.2776
Epoch 182/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5708 - mean_squared_error: 0.2905
Epoch 183/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5821 - mean_squared_error: 0.2731
Epoch 184/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5767 - mean_squared_error: 0.2614
Epoch 185/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6360 - mean_squared_error: 0.2774
Epoch 186/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5774 - mean_squared_error: 0.2418
Epoch 187/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5363 - mean_squared_error: 0.2458
Epoch 188/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5568 - mean_squared_error: 0.2736
Epoch 189/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5652 - mean_squared_error: 0.2831
Epoch 190/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5350 - mean_squared_error: 0.2775
Epoch 191/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5357 - mean_squared_error: 0.2721
Epoch 192/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.5180 - mean_squared_error: 0.2711
Epoch 193/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5192 - mean_squared_error: 0.2650
Epoch 194/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5308 - mean_squared_error: 0.3076
Epoch 195/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5046 - mean_squared_error: 0.2697
Epoch 196/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5114 - mean_squared_error: 0.2668
Epoch 197/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5580 - mean_squared_error: 0.2768
Epoch 198/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5715 - mean_squared_error: 0.2583
Epoch 199/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5632 - mean_squared_error: 0.2785
Epoch 200/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5526 - mean_squared_error: 0.2445
Epoch 201/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5517 - mean_squared_error: 0.2690
Epoch 202/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5372 - mean_squared_error: 0.2891
Epoch 203/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5400 - mean_squared_error: 0.2877
Epoch 204/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5459 - mean_squared_error: 0.2858
Epoch 205/1000
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5614 - mean_squared_error: 0.2632
Epoch 206/1000

In [351]:
transformed_predictions = model.predict(test_data)

actual_predictions = y_transformer.inverse_transform(transformed_predictions.reshape(-1,1))
rounded_actual_predictions = [ round(x,4) for x in actual_predictions.flatten()]

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

c:\Users\sohil\anaconda3\envs\AICourse\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but PowerTransformer was fitted with feature names
  warnings.warn(

In [352]:
results = pd.DataFrame({
    "Id" : test_ids,
    "SalePrice" : rounded_actual_predictions
})

results.to_csv("result.csv" , index=False)